services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: timerbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: 123

  frontend:
    build: ./front-end
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - postgres

  backend:
    build: ./BackEnd/TimerBook_API
    network_mode: host
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - APP_UPLOAD_DIR=/app/uploads
      - AI_SERVICE_URL=http://127.0.0.1:8000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5433/timerbook
      - SPRING_PROFILES_ACTIVE=dev

  python-ai:
    build: ./ia-service
    network_mode: host
    volumes:
      - ./uploads:/app/uploads
    environment:
      - UPLOADS_DIR=/app/uploads
      - OLLAMA_URL=http://127.0.0.1:11434/api/generate
    depends_on:
      - backend
    restart: on-failure

volumes:
  postgres_data:
