services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: timerbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: 123

  frontend:
    build: ./front-end
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - postgres

  backend:
    build: ./BackEnd/TimerBook_API
    ports:
      - "8080:8080"
    volumes:
     - ./uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - APP_UPLOAD_DIR=/app/uploads
      - SPRING_PROFILES_ACTIVE=dev
volumes:
  postgres_data: