server:
  port: 8080

spring:
  application:
    name: timerbook
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: test

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

cors:
  originPatterns: http://localhost:8080,http://localhost:3000,http://localhost:5173,http://localhost:8081,http://*:5173, http://*:8081

app:
  reminders:
    reading:
      enabled: true
      cron: "0 0 9 * * *"
      timezone: America/Sao_Paulo
      inactivity-hours: 24
      reminder-interval-minutes: 1440

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

api:
  security:
    token:
      secret: MYJWTSECRET