server:
  port: 8080

spring:
  application:
    name: timerbook
  mail:
    host: smtp.gmail.com
    port: 587
    username : # Email da conta de envio
    password: # Senha da conta de envio
    properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: test

cors:
  originPatterns: http://localhost:8080,http://localhost:3000,http://localhost:5173

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

api:
  security:
    token:
      secret: MYJWTSECRET